apiVersion: v1
kind: ServiceAccount
metadata:
  name: karoo
  namespace: karoo
  labels:
    app: karoo
  annotations:
    description: "Service account for Karoo Stratum Proxy"
automountServiceAccountToken: false